---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  shoggoth.override: |
    rewrite stop name exact ${SHOGGOTH_DOMAIN} web-internal.shoggoth.svc.cluster.local
    rewrite stop {
      name suffix ${SHOGGOTH_DOMAIN} shoggoth.svc.cluster.local
      answer auto
    }