---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: shoggoth-openbao-write
  namespace: ${SHOGGOTH_NAMESPACE}
spec:
  provider:
    vault:
      server: http://openbao:80
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: shoggoth-openbao-eso-write-token
          key: token
