load_module modules/ngx_otel_module.so;

events {
    worker_connections 1024;
}

http {
    otel_exporter {
        endpoint http://otelcol:4317;
    }
    otel_service_name angie;

    server {
        listen 80;

        server_name shoggoth.local;

        root /data/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /setup-client.sh {
            alias /data/setup-client.sh;
            default_type application/x-sh;
        }
    }

    server {
        listen 80;

        server_name apt-cache.shoggoth.local;
        location / {
            proxy_pass http://apt-cache:3142;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        client_max_body_size 10G;

        server_name docker-registry.shoggoth.local;
        location / {
            proxy_pass http://docker-registry;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name ai.shoggoth.local;
        location / {
            proxy_pass http://litellm;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name git.shoggoth.local;
        location / {
            proxy_pass http://git;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name git-pages.shoggoth.local;
        location / {
            proxy_pass http://git-pages;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name redmine.shoggoth.local;
        location / {
            proxy_pass http://redmine;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name proxpi.shoggoth.local;
        location / {
            proxy_pass http://proxpi;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name kestra.shoggoth.local;
        location / {
            proxy_pass http://kestra;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name build-cache.shoggoth.local;
        location / {
            alias /data/build_cache/;
            log_not_found off;
            dav_methods PUT DELETE;
            create_full_put_path on;
            client_max_body_size 100M;
        }
    }

    server {
        listen 80;

        server_name grafana.shoggoth.local;
        location / {
            proxy_pass http://grafana;
            include proxy-params.conf;
        }
    }
}
