events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        server_name shoggoth.local;

        root /data/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /setup-client.sh {
            alias /data/setup-client.sh;
            default_type application/x-sh;
        }
    }

    server {
        listen 80;

        server_name apt-cache.shoggoth.local;
        location / {
            proxy_pass http://apt-cache:3142;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name docker-registry.shoggoth.local;
        location / {
            proxy_pass http://docker-registry;
            include proxy-params.conf;
        }
    }

#    server {
#        listen 80;
#        listen 3128;
#
#        server_name docker-cache.shoggoth.local;
#        location / {
#            proxy_pass http://docker-cache:3128;
#            include proxy-params.conf;
#        }
#    }

    server {
        listen 80;

        server_name ollama.shoggoth.local;
        location / {
            proxy_pass http://ollama:11434;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name git.shoggoth.local;
        location / {
            proxy_pass http://git:3000;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name gitea-mcp.shoggoth.local;
        location / {
            proxy_pass http://gitea-mcp:8080;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name git-pages.shoggoth.local;
        location / {
            proxy_pass http://git-pages:3000;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name redmine.shoggoth.local;
        location / {
            proxy_pass http://redmine:3000;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name redmine-mcp.shoggoth.local;
        location / {
            proxy_pass http://redmine-mcp:8000;
            include proxy-params.conf;
            proxy_set_header X-Redmine-URL redmine;
        }
    }

    server {
        listen 80;

        server_name proxpi.shoggoth.local;
        location / {
            proxy_pass http://proxpi:5000;
            include proxy-params.conf;
        }
    }

    server {
        listen 80;

        server_name build-cache.shoggoth.local;
        location / {
            alias /data/build_cache/;
            log_not_found off;
            dav_methods PUT DELETE;
            create_full_put_path on;
            client_max_body_size 100M;
        }
    }
}

stream {
    server {
        listen 22;
        proxy_pass git:22;
    }
}
