model_list:
    - model_name: nomic-embed-text
      litellm_params:
          model: "openai/nomic-embed-text-v1.5"
          api_base: http://localai:80/v1
          api_key: "localai"

    - model_name: "localai/*"
      litellm_params:
          model: "openai/*"
          api_base: http://localai:80/v1
          api_key: "localai"
      model_info:
          supports_function_calling: true

    - model_name: "*"
      litellm_params:
          model: "openai/*"
          api_base: https://ollama.com/v1
          api_key: "${OLLAMA_CLOUD_TOKEN}"
      model_info:
          supports_function_calling: true

litellm_settings:
    callbacks:
        - prometheus
        - otel
    drop_params: true

general_settings:
    store_model_in_db: true

mcp_servers:
    mcp_gitea:
        url: "http://mcp-gitea:80/mcp"
        transport: "http"
        description: "Gitea MCP server"
        auth_type: "bearer_token"
        auth_value: "${GITEA_SERVER_TOKEN}"
        allow_all_keys: true

    basic_memory:
        url: "http://basic-memory:80/mcp"
        transport: "http"
        description: "Basic Memory MCP server"
        allow_all_keys: true
