local-zone: "${SHOGGOTH_DOMAIN}." redirect
local-data: "${SHOGGOTH_DOMAIN}. 86400 IN A 172.20.0.80"
local-zone: "dns.${SHOGGOTH_DOMAIN}." redirect
local-data: "dns.${SHOGGOTH_DOMAIN}. 86400 IN A 172.20.0.53"
local-zone: "wireguard.${SHOGGOTH_DOMAIN}." redirect
local-data: "wireguard.${SHOGGOTH_DOMAIN}. 86400 IN A 172.20.0.2"
local-zone: "apt-cache.${SHOGGOTH_DOMAIN}." redirect
local-data: "apt-cache.${SHOGGOTH_DOMAIN}. 86400 IN A 172.20.0.40"
local-zone: "docker-cache.${SHOGGOTH_DOMAIN}." redirect
local-data: "docker-cache.${SHOGGOTH_DOMAIN}. 86400 IN A 172.20.0.30"
local-zone: "otelcol.${SHOGGOTH_DOMAIN}." redirect
local-data: "otelcol.${SHOGGOTH_DOMAIN}. 86400 IN A 172.20.0.60"