server:
  verbosity: 1
  interface: 0.0.0.0
  access-control: 0.0.0.0/0 allow
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  hide-identity: yes
  hide-version: yes

include: /opt/unbound/etc/unbound/local-data.conf
include: /opt/unbound/etc/unbound/unbound-nxdomain.blacklist