id: redmine-issue-updated
namespace: shoggoth

concurrency:
  limit: 2

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: redmine-issue-updated

tasks:
  - id: process_issue
    type: io.kestra.plugin.docker.Run
    containerImage: docker-registry.shoggoth.local/slave_noble:latest
    commands:
      - echo
      - "Processing Redmine issue ID: {{ trigger.body.payload.issue.id }}"
