id: redmine-task-processor
namespace: shoggoth
disabled: true

concurrency:
  limit: 1

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/10 * * * *"
    stopAfter:
      - FAILED
      - KILLED

tasks:
  - id: list_in_progress_tasks
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      volumes:
        - "{{ envs.shoggoth_root }}/private/apt-cache.conf:/etc/apt/apt.conf.d/00-shoggoth-apt-cache"
        - "{{ envs.shoggoth_root }}/private/env:/env"
        - "{{ envs.shoggoth_root }}/private/resolv.conf:/etc/resolv.conf"
        - "{{ envs.ssh_auth_sock }}:{{ envs.ssh_auth_sock }}"
        - "shoggoth_ci_cache:/cache"
      pullPolicy: ALWAYS
    containerImage: docker-registry.shoggoth.local/slave_noble:latest
    commands:
      - "bash -c 'set -a && source /env && set +a && redmine issues list --status=\"In Progress\" --limit=1 --output=json' > /home/ccws/tasks.json"
      - "bash -c 'set -a && source /env && set +a && redmine issues update `jq '.[0].id' < /home/ccws/tasks.json` --status=Resolved'"
      - "bash -c 'set -a && source /env && set +a && echo \"Selected task ID: `jq '.[0].id' < /home/ccws/tasks.json`\"'"
