# Shoggoth NixOS module for the host (common part)
#
# Copy this file to /etc/nixos/shoggoth.nix on the host and add the following
# lines to /etc/nixos/configuration.nix:
#
#   imports = [ ./shoggoth.nix ./<instance>-ports.nix ];
#
# The <instance>-ports.nix file is generated by `make host_install_nixos`.

{ config, pkgs, ... }:

let
  domain = "${SHOGGOTH_DOMAIN}";
  registryPort = "${REGISTRY_PORT}";
  k3sRegistries = pkgs.writeText "registries.yaml" ''
    mirrors:
      docker.io:
        endpoint:
          - "http://localhost:${registryPort}"
      ghcr.io:
        endpoint:
          - "http://localhost:${registryPort}"
      gcr.io:
        endpoint:
          - "http://localhost:${registryPort}"
      quay.io:
        endpoint:
          - "http://localhost:${registryPort}"
      mcr.microsoft.com:
        endpoint:
          - "http://localhost:${registryPort}"
      codeberg.org:
        endpoint:
          - "http://localhost:${registryPort}"
      docker.gitea.com:
        endpoint:
          - "http://localhost:${registryPort}"
      docker.angie.software:
        endpoint:
          - "http://localhost:${registryPort}"
      public.ecr.aws:
        endpoint:
          - "http://localhost:${registryPort}"
      registry.${domain}:
        endpoint:
          - "http://localhost:${registryPort}"
    configs:
      "localhost:${registryPort}":
        tls:
          insecure_skip_verify: true
      registry.${domain}:
        tls:
          insecure_skip_verify: true
  '';
in {
  services.k3s = {
    enable = true;
    role = "server";
    extraFlags = "--disable=traefik --disable=servicelb";
  };

  environment.systemPackages = with pkgs; [
    k3s
    kubectl
    kubernetes-helm
  ];

  # K3s API server is accessed via SSH tunnel, not exposed on the network.

  # K3s uses its own containerd instance. Configure containerd registries
  # so K3s pulls images through the shoggoth container-cache proxy and treats
  # the internal registry as insecure (HTTP, self-signed CA).
  environment.etc."rancher/k3s/registries.yaml".source = k3sRegistries;

  virtualisation.docker.enable = true;
  virtualisation.docker.daemon.settings = {
    insecure-registries = [ "localhost" "localhost:${registryPort}" "registry.${domain}" ];
    registry-mirrors = [ "http://localhost:${registryPort}" ];
  };

  networking.firewall.trustedInterfaces = [ "cni0" ];
  networking.firewall.extraCommands = ''
    iptables -w -A FORWARD -i wg0 -o cni0 -j ACCEPT
  '';
}
