---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ca-passphrase
  namespace: ${SHOGGOTH_NAMESPACE}
spec:
  secretStoreRef:
    name: shoggoth-openbao
    kind: SecretStore
  target:
    name: ca-passphrase
    creationPolicy: Owner
  data:
    - secretKey: passphrase
      remoteRef:
        key: ca/passphrase
        property: value
  refreshInterval: 5m
