---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cdash-api-token
  namespace: ${SHOGGOTH_NAMESPACE}
spec:
  secretStoreRef:
    name: shoggoth-openbao
    kind: SecretStore
  target:
    name: cdash-api-token
    creationPolicy: Orphan
  data:
    - secretKey: token
      remoteRef:
        key: cdash/api-token
        property: value
  refreshInterval: 5m
