---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner-token
  namespace: ${SHOGGOTH_NAMESPACE}
spec:
  secretStoreRef:
    name: shoggoth-openbao
    kind: SecretStore
  target:
    name: gitea-runner-token
    creationPolicy: Orphan
  data:
    - secretKey: token
      remoteRef:
        key: gitea/runner-token
        property: value
  refreshInterval: 5m
