---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openldap-slave-password
  namespace: ${SHOGGOTH_NAMESPACE}
spec:
  secretStoreRef:
    name: shoggoth-openbao
    kind: SecretStore
  target:
    name: openldap-slave-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: openldap/slave-password
        property: value
  refreshInterval: 5m
