---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redmine-secret-key-base
  namespace: ${SHOGGOTH_NAMESPACE}
spec:
  secretStoreRef:
    name: shoggoth-openbao
    kind: SecretStore
  target:
    name: redmine-secret-key-base
    creationPolicy: Owner
  data:
    - secretKey: secret-key-base
      remoteRef:
        key: redmine/secret-key-base
        property: value
  refreshInterval: 5m
