---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wireguard-admin-password
  namespace: ${SHOGGOTH_NAMESPACE}
spec:
  secretStoreRef:
    name: shoggoth-openbao
    kind: SecretStore
  target:
    name: wireguard-admin-password
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: wireguard/admin-password
        property: value
  refreshInterval: 5m
