auth_enabled: false

server:
    http_listen_port: 3100
    grpc_listen_port: 9096
    log_level: warn

common:
    instance_addr: 127.0.0.1
    path_prefix: /loki
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
    replication_factor: 1
    ring:
        kvstore:
            store: inmemory

query_range:
    results_cache:
        cache:
            embedded_cache:
                enabled: true
                max_size_mb: 100

schema_config:
    configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
              prefix: index_
              period: 24h

storage_config:
    filesystem:
        directory: /loki/storage
    tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache

distributor:
    otlp_config:
        default_resource_attributes_as_index_labels:
            - service.name
            - service.namespace
            - service.instance.id
            - container.name
            - deployment.environment.name
            - session.id
            - compose.service

limits_config:
    retention_period: 8760h
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_query_length: 721h

compactor:
    working_directory: /loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    delete_request_store: filesystem

analytics:
    reporting_enabled: false
